/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * penonton1.java
 *
 * Created on May 12, 2014, 7:38:30 AM
 */

package undian;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import socket.socketPenonton;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Properties;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import libs.EscapableFrame;
import libs.buttonMakeOver;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;
import windowUtilities.WindowUtilities;

/**
 *
 * @author Kiezie
 */
public class penonton extends EscapableFrame {
    
    Timer timer1, timer2;
    int interval = 50;
    BufferedImage image;
    Image scaledImage;
    public String opertor_ip  = "127.0.0.1";
    public static String session = "";
    public static int no_dari = 1;
    public static int no_sampai = 999;
    
    public int screen;
    public static boolean is_running = false;
    
    public static String string_pemenang = "";
    public static ArrayList<String> no_undangan;
    
    class pemenang {
        String no_undian;
        String kategori;
        String hadiah;
        String urutan_ke;
        
        pemenang(String no_undian, String kategori, String hadiah, String urutan_ke) {
            this.no_undian = no_undian;
            this.kategori = kategori;
            this.hadiah = hadiah;
            this.urutan_ke = urutan_ke;
        }
         
        String getNo_undian() {
            return this.no_undian;
        }
        
        String getKategori() {
            return this.kategori;
        }
        
        String getHadiah() {
            return this.hadiah;
        }
        
        
        String getUrutan_ke() {
            return this.urutan_ke;
        }
    }
    
    public static ArrayList<pemenang> listpemenang = new ArrayList<pemenang>();
    
    public static int time_stop = 5;
    
    public penonton(int screen) {
        this.screen = screen;
        readOperatorFile();
        new socketPenonton(this);        
    }

    public void showJPenonton() {
        initComponents();
        
        if(cekScreenLength()>1) {
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            GraphicsDevice[] gd = ge.getScreenDevices();
            setLocation(gd[1].getDefaultConfiguration().getBounds().x, getY());
        }

        setVisible(true);        
    }

    public static int cekScreenLength() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] gs = ge.getScreenDevices();

        return gs.length;
    }

    private void readOperatorFile() {
        Properties prop = new Properties();
	InputStream input = null;
	try {
            input = new FileInputStream("operator.properties");
            prop.load(input);

            opertor_ip = prop.getProperty("operator");
	} catch (IOException ex) {
            ex.printStackTrace();
	} finally {
            if (input != null) {
                try {
                    input.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
	}
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbl_nama_event = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_kategori = new javax.swing.JLabel();
        lbl_hadiah = new javax.swing.JLabel();
        lbl_waktu = new javax.swing.JLabel();
        btn_acak = new buttonMakeOver();
        lbl_waktu1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_no_undian_reguler_07 = new javax.swing.JLabel();
        lbl_separator_no_undian_reguler_03 = new javax.swing.JLabel();
        lbl_no_undian_reguler_08 = new javax.swing.JLabel();
        lbl_no_undian_reguler_09 = new javax.swing.JLabel();
        lbl_separator_no_undian_reguler_04 = new javax.swing.JLabel();
        lbl_no_undian_reguler_06 = new javax.swing.JLabel();
        lbl_no_undian_reguler_10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_no_undian_reguler_02 = new javax.swing.JLabel();
        lbl_separator_no_undian_reguler_01 = new javax.swing.JLabel();
        lbl_no_undian_reguler_03 = new javax.swing.JLabel();
        lbl_no_undian_reguler_04 = new javax.swing.JLabel();
        lbl_separator_no_undian_reguler_02 = new javax.swing.JLabel();
        lbl_no_undian_reguler_01 = new javax.swing.JLabel();
        lbl_no_undian_reguler_05 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lbl_separator_no_undian_utama_01 = new javax.swing.JLabel();
        lbl_no_undian_utama = new javax.swing.JLabel();
        lbl_separator_no_undian_utama_02 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.darkGray);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);

        jPanel2.setBackground(java.awt.Color.darkGray);

        jPanel1.setBackground(java.awt.Color.darkGray);

        lbl_nama_event.setBackground(java.awt.Color.darkGray);
        lbl_nama_event.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbl_nama_event.setForeground(java.awt.Color.yellow);
        lbl_nama_event.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_nama_event.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_nama_event.setOpaque(true);

        lbl_logo.setBackground(java.awt.Color.darkGray);
        lbl_logo.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nama_event, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_nama_event, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        lbl_kategori.setBackground(java.awt.Color.darkGray);
        lbl_kategori.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbl_kategori.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kategori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_kategori.setText("HADIAH UTAMA");
        lbl_kategori.setOpaque(true);

        lbl_hadiah.setBackground(java.awt.Color.darkGray);
        lbl_hadiah.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbl_hadiah.setForeground(new java.awt.Color(255, 255, 255));
        lbl_hadiah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_hadiah.setText("MOBIL AVANZA");
        lbl_hadiah.setOpaque(true);

        lbl_waktu.setBackground(java.awt.Color.darkGray);
        lbl_waktu.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_waktu.setOpaque(true);

        btn_acak.setIcon(new javax.swing.ImageIcon("images\\ACAK.png")); // NOI18N
        btn_acak.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_acak.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        btn_acak.setForeground(new java.awt.Color(204, 102, 0));
        btn_acak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acakActionPerformed(evt);
            }
        });

        lbl_waktu1.setBackground(java.awt.Color.darkGray);
        lbl_waktu1.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_waktu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_waktu1.setOpaque(true);

        jPanel5.setBackground(java.awt.Color.darkGray);

        lbl_no_undian_reguler_07.setBackground(new java.awt.Color(102, 102, 255));
        lbl_no_undian_reguler_07.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_no_undian_reguler_07.setForeground(new java.awt.Color(204, 255, 153));
        lbl_no_undian_reguler_07.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_no_undian_reguler_07.setText("000");
        lbl_no_undian_reguler_07.setOpaque(true);

        lbl_separator_no_undian_reguler_03.setBackground(new java.awt.Color(64, 64, 64));
        lbl_separator_no_undian_reguler_03.setFont(new java.awt.Font("Tahoma", 1, 120)); // NOI18N
        lbl_separator_no_undian_reguler_03.setForeground(new java.awt.Color(255, 255, 0));
        lbl_separator_no_undian_reguler_03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_separator_no_undian_reguler_03.setOpaque(true);

        lbl_no_undian_reguler_08.setBackground(new java.awt.Color(102, 102, 255));
        lbl_no_undian_reguler_08.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_no_undian_reguler_08.setForeground(new java.awt.Color(204, 255, 153));
        lbl_no_undian_reguler_08.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_no_undian_reguler_08.setText("000");
        lbl_no_undian_reguler_08.setOpaque(true);

        lbl_no_undian_reguler_09.setBackground(new java.awt.Color(102, 102, 255));
        lbl_no_undian_reguler_09.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_no_undian_reguler_09.setForeground(new java.awt.Color(204, 255, 153));
        lbl_no_undian_reguler_09.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_no_undian_reguler_09.setText("000");
        lbl_no_undian_reguler_09.setOpaque(true);

        lbl_separator_no_undian_reguler_04.setBackground(new java.awt.Color(64, 64, 64));
        lbl_separator_no_undian_reguler_04.setFont(new java.awt.Font("Tahoma", 1, 120)); // NOI18N
        lbl_separator_no_undian_reguler_04.setForeground(new java.awt.Color(255, 255, 0));
        lbl_separator_no_undian_reguler_04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_separator_no_undian_reguler_04.setOpaque(true);

        lbl_no_undian_reguler_06.setBackground(new java.awt.Color(102, 102, 255));
        lbl_no_undian_reguler_06.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_no_undian_reguler_06.setForeground(new java.awt.Color(204, 255, 153));
        lbl_no_undian_reguler_06.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_no_undian_reguler_06.setText("000");
        lbl_no_undian_reguler_06.setOpaque(true);

        lbl_no_undian_reguler_10.setBackground(new java.awt.Color(102, 102, 255));
        lbl_no_undian_reguler_10.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_no_undian_reguler_10.setForeground(new java.awt.Color(204, 255, 153));
        lbl_no_undian_reguler_10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_no_undian_reguler_10.setText("000");
        lbl_no_undian_reguler_10.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lbl_separator_no_undian_reguler_03, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_no_undian_reguler_06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_no_undian_reguler_07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_no_undian_reguler_08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_no_undian_reguler_09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_no_undian_reguler_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_separator_no_undian_reguler_04, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_no_undian_reguler_07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_separator_no_undian_reguler_03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_separator_no_undian_reguler_04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_no_undian_reguler_09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_no_undian_reguler_08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_no_undian_reguler_06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_no_undian_reguler_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(java.awt.Color.darkGray);

        lbl_no_undian_reguler_02.setBackground(new java.awt.Color(102, 102, 255));
        lbl_no_undian_reguler_02.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_no_undian_reguler_02.setForeground(new java.awt.Color(204, 255, 153));
        lbl_no_undian_reguler_02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_no_undian_reguler_02.setText("000");
        lbl_no_undian_reguler_02.setOpaque(true);

        lbl_separator_no_undian_reguler_01.setBackground(new java.awt.Color(64, 64, 64));
        lbl_separator_no_undian_reguler_01.setFont(new java.awt.Font("Tahoma", 1, 120)); // NOI18N
        lbl_separator_no_undian_reguler_01.setForeground(new java.awt.Color(255, 255, 0));
        lbl_separator_no_undian_reguler_01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_separator_no_undian_reguler_01.setOpaque(true);

        lbl_no_undian_reguler_03.setBackground(new java.awt.Color(102, 102, 255));
        lbl_no_undian_reguler_03.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_no_undian_reguler_03.setForeground(new java.awt.Color(204, 255, 153));
        lbl_no_undian_reguler_03.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_no_undian_reguler_03.setText("000");
        lbl_no_undian_reguler_03.setOpaque(true);

        lbl_no_undian_reguler_04.setBackground(new java.awt.Color(102, 102, 255));
        lbl_no_undian_reguler_04.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_no_undian_reguler_04.setForeground(new java.awt.Color(204, 255, 153));
        lbl_no_undian_reguler_04.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_no_undian_reguler_04.setText("000");
        lbl_no_undian_reguler_04.setOpaque(true);

        lbl_separator_no_undian_reguler_02.setBackground(new java.awt.Color(64, 64, 64));
        lbl_separator_no_undian_reguler_02.setFont(new java.awt.Font("Tahoma", 1, 120)); // NOI18N
        lbl_separator_no_undian_reguler_02.setForeground(new java.awt.Color(255, 255, 0));
        lbl_separator_no_undian_reguler_02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_separator_no_undian_reguler_02.setOpaque(true);

        lbl_no_undian_reguler_01.setBackground(new java.awt.Color(102, 102, 255));
        lbl_no_undian_reguler_01.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_no_undian_reguler_01.setForeground(new java.awt.Color(204, 255, 153));
        lbl_no_undian_reguler_01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_no_undian_reguler_01.setText("000");
        lbl_no_undian_reguler_01.setOpaque(true);

        lbl_no_undian_reguler_05.setBackground(new java.awt.Color(102, 102, 255));
        lbl_no_undian_reguler_05.setFont(new java.awt.Font("Tahoma", 1, 90)); // NOI18N
        lbl_no_undian_reguler_05.setForeground(new java.awt.Color(204, 255, 153));
        lbl_no_undian_reguler_05.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_no_undian_reguler_05.setText("000");
        lbl_no_undian_reguler_05.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lbl_separator_no_undian_reguler_01, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_no_undian_reguler_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_no_undian_reguler_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_no_undian_reguler_03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_no_undian_reguler_04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_no_undian_reguler_05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lbl_separator_no_undian_reguler_02, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_no_undian_reguler_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_separator_no_undian_reguler_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_separator_no_undian_reguler_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_no_undian_reguler_04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_no_undian_reguler_03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_no_undian_reguler_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_no_undian_reguler_05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(java.awt.Color.darkGray);

        lbl_separator_no_undian_utama_01.setBackground(new java.awt.Color(64, 64, 64));
        lbl_separator_no_undian_utama_01.setFont(new java.awt.Font("Tahoma", 1, 120)); // NOI18N
        lbl_separator_no_undian_utama_01.setForeground(new java.awt.Color(255, 255, 0));
        lbl_separator_no_undian_utama_01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_separator_no_undian_utama_01.setOpaque(true);

        lbl_no_undian_utama.setBackground(new java.awt.Color(102, 102, 255));
        lbl_no_undian_utama.setFont(new java.awt.Font("Tahoma", 1, 120)); // NOI18N
        lbl_no_undian_utama.setForeground(new java.awt.Color(204, 255, 153));
        lbl_no_undian_utama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_no_undian_utama.setText("000");
        lbl_no_undian_utama.setOpaque(true);

        lbl_separator_no_undian_utama_02.setBackground(new java.awt.Color(64, 64, 64));
        lbl_separator_no_undian_utama_02.setFont(new java.awt.Font("Tahoma", 1, 120)); // NOI18N
        lbl_separator_no_undian_utama_02.setForeground(new java.awt.Color(255, 255, 0));
        lbl_separator_no_undian_utama_02.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_separator_no_undian_utama_02.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lbl_separator_no_undian_utama_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_no_undian_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_separator_no_undian_utama_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_separator_no_undian_utama_01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_separator_no_undian_utama_02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_no_undian_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(java.awt.Color.darkGray);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbl_waktu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_acak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_waktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_hadiah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_kategori, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_hadiah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_waktu1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(lbl_waktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_acak, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(357, Short.MAX_VALUE))
        );

        lbl_kategori.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_acakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acakActionPerformed
        // TODO add your handling code here:
        
        if(!is_running) {
            //start
            is_running = true;
            
            timer1 = new Timer();
            timer1.schedule(new RemindTask(), 0, 50);
            
            timer2 = new Timer();
            timer2.schedule(new StopTask(), time_stop*1000);
            btn_acak.setIcon(new javax.swing.ImageIcon("images\\STOP.png"));
        } else {
            //stop
            timer2.cancel();
            is_running = false;
            btn_acak.setVisible(false);
            btn_acak.setIcon(new javax.swing.ImageIcon("images\\ACAK.png"));
        }
        
    }//GEN-LAST:event_btn_acakActionPerformed

    /**
    * @param args the command line arguments
    */

    public void loadBattle(JSONObject json) {

        try {
            String nama_event = json.getString("nama_event");
            String kategori = json.getString("kategori");
            String hadiah = json.getString("hadiah");
            JSONArray data_undangan = json.getJSONArray("undangan");
            
            no_undangan = new ArrayList<String>();
            for(int i=0; i<data_undangan.length(); i++) {
                JSONObject rec = data_undangan.getJSONObject(i);
                no_undangan.add(rec.getString("no_undian"));
            }
            
            JSONArray data_pemenang = json.getJSONArray("pemenang");
            listpemenang = new ArrayList<pemenang>();
            for(int i=0; i<data_pemenang.length(); i++) {
                JSONObject rec = data_pemenang.getJSONObject(i);
                listpemenang.add(new pemenang(rec.getString("no_undian"), rec.getString("kategori"), rec.getString("hadiah"), rec.getString("urutan_ke")));
            }
            
            no_dari = json.getInt("no_dari");
            no_sampai = json.getInt("no_sampai");
            time_stop = json.getInt("time_stop");
            lbl_nama_event.setText(nama_event);
            lbl_kategori.setText(kategori);
            lbl_hadiah.setText(hadiah);
            
            jPanel4.setVisible(kategori.equalsIgnoreCase("HADIAH REGULER"));
            jPanel5.setVisible(kategori.equalsIgnoreCase("HADIAH REGULER"));
            jPanel6.setVisible(kategori.equalsIgnoreCase("HADIAH UTAMA"));
            
            lbl_no_undian_reguler_01.setText("000");
            lbl_no_undian_reguler_02.setText("000");
            lbl_no_undian_reguler_03.setText("000");
            lbl_no_undian_reguler_04.setText("000");
            lbl_no_undian_reguler_05.setText("000");
            lbl_no_undian_reguler_06.setText("000");
            lbl_no_undian_reguler_07.setText("000");
            lbl_no_undian_reguler_08.setText("000");
            lbl_no_undian_reguler_09.setText("000");
            lbl_no_undian_reguler_10.setText("000");
            lbl_no_undian_utama.setText("000");
            
            btn_acak.setVisible(true);
        } catch (JSONException ex) {
            Logger.getLogger(penonton.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void loadLogo() {
        try {
            image = ImageIO.read(new File("images/temp.jpg"));
            scaledImage = image.getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(), Image.SCALE_SMOOTH);
            lbl_logo.setIcon(new ImageIcon(scaledImage));
        } catch (IOException ex) {
            Logger.getLogger(penonton.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public static void main(String args[]) {
        WindowUtilities.setNativeLookAndFeel();
        new penonton(1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acak;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JLabel lbl_hadiah;
    public javax.swing.JLabel lbl_kategori;
    public javax.swing.JLabel lbl_logo;
    public javax.swing.JLabel lbl_nama_event;
    public javax.swing.JLabel lbl_no_undian_reguler_01;
    public javax.swing.JLabel lbl_no_undian_reguler_02;
    public javax.swing.JLabel lbl_no_undian_reguler_03;
    public javax.swing.JLabel lbl_no_undian_reguler_04;
    public javax.swing.JLabel lbl_no_undian_reguler_05;
    public javax.swing.JLabel lbl_no_undian_reguler_06;
    public javax.swing.JLabel lbl_no_undian_reguler_07;
    public javax.swing.JLabel lbl_no_undian_reguler_08;
    public javax.swing.JLabel lbl_no_undian_reguler_09;
    public javax.swing.JLabel lbl_no_undian_reguler_10;
    public javax.swing.JLabel lbl_no_undian_utama;
    public javax.swing.JLabel lbl_separator_no_undian_reguler_01;
    public javax.swing.JLabel lbl_separator_no_undian_reguler_02;
    public javax.swing.JLabel lbl_separator_no_undian_reguler_03;
    public javax.swing.JLabel lbl_separator_no_undian_reguler_04;
    public javax.swing.JLabel lbl_separator_no_undian_utama_01;
    public javax.swing.JLabel lbl_separator_no_undian_utama_02;
    public javax.swing.JLabel lbl_waktu;
    public javax.swing.JLabel lbl_waktu1;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean close() {

        String str = JOptionPane.showInputDialog(this, "IP Server: ", opertor_ip);
        if(str != null) {
            opertor_ip = str;
            writeIp(opertor_ip);
        }

        return false;
    }

    public void writeIp(String server) {
        Properties prop = new Properties();
	OutputStream output = null;

	try {
            output = new FileOutputStream("operator.properties");

            // set the properties value
            prop.setProperty("operator", server);

            // save properties to project root folder
            prop.store(output, null);


	} catch (IOException io) {
            io.printStackTrace();
	} finally {
            if (output != null) {
                try {
                    output.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
	}
    }
    
    public static boolean stringContainsItemFromList(String inputString) {
        for(int i =0; i<listpemenang.size(); i++) {
            //System.out.println(inputString + " CAS "+listpemenang.get(i).getNo_undian());
            if(inputString.equalsIgnoreCase(listpemenang.get(i).getNo_undian()))  {
                return true;
            }
        }
    
        return false;
    }
    
    public static boolean stringContainsNoUndanganFromList(String inputString) {
        for(int i =0; i<no_undangan.size(); i++) {
            //System.out.println(inputString + " CAS "+listpemenang.get(i).getNo_undian());
            if(inputString.equalsIgnoreCase(no_undangan.get(i)))  {
                return true;
            }
        }
    
        return false;
    }
    
    
    class RemindTask extends TimerTask {
        public void run() {
            /*if(!is_running) {
                timer1.cancel();
            }*/
            
            String kategori = lbl_kategori.getText().toString();
            String data_pemenang = "";
            if(kategori.equalsIgnoreCase("HADIAH REGULER")) {
                String val_1 = getRandomNumber();
                if(!is_running) {
                    listpemenang.add(new pemenang(val_1, lbl_kategori.getText().toString(), lbl_hadiah.getText().toString(), ""));
                    data_pemenang+="{no_undian: \""+val_1+"\", kategori: \""+lbl_kategori.getText().toString()+"\", hadiah: \""+lbl_hadiah.getText().toString()+"\", urutan_ke: \"\"}, ";
                }

                String val_2 = getRandomNumber();
                if(!is_running) {
                    listpemenang.add(new pemenang(val_2, lbl_kategori.getText().toString(), lbl_hadiah.getText().toString(), ""));
                    data_pemenang+="{no_undian: \""+val_2+"\", kategori: \""+lbl_kategori.getText().toString()+"\", hadiah: \""+lbl_hadiah.getText().toString()+"\", urutan_ke: \"\"}, ";
                }

                String val_3 = getRandomNumber();
                if(!is_running) {
                    listpemenang.add(new pemenang(val_3, lbl_kategori.getText().toString(), lbl_hadiah.getText().toString(), ""));
                    data_pemenang+="{no_undian: \""+val_3+"\", kategori: \""+lbl_kategori.getText().toString()+"\", hadiah: \""+lbl_hadiah.getText().toString()+"\", urutan_ke: \"\"}, ";
                }

                String val_4 = getRandomNumber();
                if(!is_running) {
                    listpemenang.add(new pemenang(val_4, lbl_kategori.getText().toString(), lbl_hadiah.getText().toString(), ""));
                    data_pemenang+="{no_undian: \""+val_4+"\", kategori: \""+lbl_kategori.getText().toString()+"\", hadiah: \""+lbl_hadiah.getText().toString()+"\", urutan_ke: \"\"}, ";
                }

                String val_5 = getRandomNumber();
                if(!is_running) {
                    listpemenang.add(new pemenang(val_5, lbl_kategori.getText().toString(), lbl_hadiah.getText().toString(), ""));
                    data_pemenang+="{no_undian: \""+val_5+"\", kategori: \""+lbl_kategori.getText().toString()+"\", hadiah: \""+lbl_hadiah.getText().toString()+"\", urutan_ke: \"\"}, ";
                }

                String val_6 = getRandomNumber();
                if(!is_running) {
                    listpemenang.add(new pemenang(val_6, lbl_kategori.getText().toString(), lbl_hadiah.getText().toString(), ""));
                    data_pemenang+="{no_undian: \""+val_6+"\", kategori: \""+lbl_kategori.getText().toString()+"\", hadiah: \""+lbl_hadiah.getText().toString()+"\", urutan_ke: \"\"}, ";
                }

                String val_7 = getRandomNumber();
                if(!is_running) {
                    listpemenang.add(new pemenang(val_7, lbl_kategori.getText().toString(), lbl_hadiah.getText().toString(), ""));
                    data_pemenang+="{no_undian: \""+val_7+"\", kategori: \""+lbl_kategori.getText().toString()+"\", hadiah: \""+lbl_hadiah.getText().toString()+"\", urutan_ke: \"\"}, ";
                }

                String val_8 = getRandomNumber();
                if(!is_running) {
                    listpemenang.add(new pemenang(val_8, lbl_kategori.getText().toString(), lbl_hadiah.getText().toString(), ""));
                    data_pemenang+="{no_undian: \""+val_8+"\", kategori: \""+lbl_kategori.getText().toString()+"\", hadiah: \""+lbl_hadiah.getText().toString()+"\", urutan_ke: \"\"}, ";
                }

                String val_9 = getRandomNumber();
                if(!is_running) {
                    listpemenang.add(new pemenang(val_9, lbl_kategori.getText().toString(), lbl_hadiah.getText().toString(), ""));
                    data_pemenang+="{no_undian: \""+val_9+"\", kategori: \""+lbl_kategori.getText().toString()+"\", hadiah: \""+lbl_hadiah.getText().toString()+"\", urutan_ke: \"\"}, ";
                }

                String val_10 = getRandomNumber();
                if(!is_running) {
                    listpemenang.add(new pemenang(val_10, lbl_kategori.getText().toString(), lbl_hadiah.getText().toString(), ""));
                    data_pemenang+="{no_undian: \""+val_10+"\", kategori: \""+lbl_kategori.getText().toString()+"\", hadiah: \""+lbl_hadiah.getText().toString()+"\", urutan_ke: \"\"}";
                }

                lbl_no_undian_reguler_01.setText(val_1);
                lbl_no_undian_reguler_02.setText(val_2);
                lbl_no_undian_reguler_03.setText(val_3);
                
                lbl_no_undian_reguler_04.setText(val_4);
                lbl_no_undian_reguler_05.setText(val_5);
                lbl_no_undian_reguler_06.setText(val_6);
                
                lbl_no_undian_reguler_07.setText(val_7);
                lbl_no_undian_reguler_08.setText(val_8);
                lbl_no_undian_reguler_09.setText(val_9);
                
                lbl_no_undian_reguler_10.setText(val_10);
            } else {
                String val = getRandomNumber();
                if(!is_running) {
                    listpemenang.add(new pemenang(val, lbl_kategori.getText().toString(), lbl_hadiah.getText().toString(), ""));
                    data_pemenang+="{no_undian: \""+val+"\", kategori: \""+lbl_kategori.getText().toString()+"\", hadiah: \""+lbl_hadiah.getText().toString()+"\", urutan_ke: \"\"}";
                }
                lbl_no_undian_utama.setText(val);
            }
            
            if(!is_running) {
                timer1.cancel();
                string_pemenang = data_pemenang;
                //btn_acak.setVisible(true);
            }
            
        }
    }
    
    
    
    class StopTask extends TimerTask {
        public void run() {
            timer2.cancel();
            is_running = false;
            btn_acak.setVisible(false);
            btn_acak.setIcon(new javax.swing.ImageIcon("images\\ACAK.png"));
        }
    }
    
    public static String getRandomNumber() {
        while(true) {
            String val = String.valueOf(randInt(no_dari, no_sampai));
            int val_length = val.length();
            for(int i=0; i<3-val_length; i++){
                val="0"+val;
            }
            
            if(!stringContainsItemFromList(val) && stringContainsNoUndanganFromList(val)) {
                return val;
            }
        }
    }
    
    
    public static int randInt(int min, int max) {

        // Usually this can be a field rather than a method variable
        Random rand = new Random();

        // nextInt is normally exclusive of the top value,
        // so add 1 to make it inclusive
        int randomNum = rand.nextInt((max - min) + 1) + min;

        return randomNum;
    }

}
