/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * waitingdialog.java
 *
 * Created on May 16, 2014, 10:18:01 PM
 */

package undian;

import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Kiezie
 */
public class waitingdialog extends javax.swing.JPanel implements Runnable {
    Thread t;
    public JDialog dlg;
    /** Creates new form waitingdialog */
    public waitingdialog(JFrame parent) {
        initComponents();

        dlg = new JDialog(parent);
        t = new Thread(this, "Thread hash and rnd...");
        t.start();
    }

     public void run() {
        dlg.add(this);
        dlg.setSize(321, 91);
        dlg.setLocationRelativeTo(null);
        dlg.setModal(true);
        dlg.setUndecorated(true);
        dlg.setVisible(true);
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tunggu Sebentar...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


}
